# Generated by Django 5.2 on 2025-04-17 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('working_month', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='شناسه')),
                ('employee_workload_first_name', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='نام')),
                ('employee_workload_last_name', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='نام خانوادگی')),
                ('employee_workload_national_code', models.CharField(blank=True, editable=False, max_length=10, null=True, verbose_name='کد ملی')),
                ('employee_workload_personnel_code', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='کد پرسنلی')),
                ('employee_workload_work_days', models.SmallIntegerField(blank=True, null=True, verbose_name='کارکرد (روز)')),
                ('employee_workload_overtime_hours', models.SmallIntegerField(blank=True, null=True, verbose_name='اضافه کار (ساعت)')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='کارمند')),
                ('employee_workload_working_month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='working_month.workingmonth', verbose_name='ماه کاری')),
            ],
        ),
    ]
