# Generated by Django 5.2 on 2025-04-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_workload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkload',
            name='employee_workload_working_month',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ماه کاری'),
        ),
    ]
