# Generated by Django 5.2 on 2025-04-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_workload', '0003_alter_employeeworkload_employee_workload_working_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeworkload',
            options={'verbose_name': 'کارکرد کارمند', 'verbose_name_plural': 'کارکرد پرسنل'},
        ),
        migrations.AlterModelTable(
            name='employeeworkload',
            table='employee_workload',
        ),
    ]
