# Generated by Django 5.2 on 2025-04-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_tax_threshold', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarytaxthreshold',
            name='salary_tax_threshold_base_year',
            field=models.DateField(default='1403-01-01', verbose_name='سال پایه'),
        ),
    ]
