# Generated by Django 5.2 on 2025-04-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary_tax_threshold', '0002_alter_salarytaxthreshold_salary_tax_threshold_base_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarytaxthreshold',
            options={'verbose_name': 'حد نصاب مالیاتی', 'verbose_name_plural': 'حد نصاب های مالیاتی'},
        ),
    ]
