# Generated by Django 5.2 on 2025-04-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_national_code', models.CharField(blank=True, max_length=10, null=True)),
                ('employee_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_personnel_code', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
