# Generated by Django 5.2 on 2025-04-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'کارمند', 'verbose_name_plural': 'پرسنل'},
        ),
    ]
