# Generated by Django 5.2 on 2025-04-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryItem',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('english_name', models.CharField(max_length=50, verbose_name='نام انگلیسی')),
                ('persian_name', models.CharField(max_length=50, verbose_name='نام فارسی')),
                ('include_in_base_wage', models.BooleanField(default=False, verbose_name='درج در حقوق مبنا')),
                ('include_in_insurance', models.BooleanField(default=False, verbose_name='شامل بیمه')),
                ('include_in_tax', models.BooleanField(default=False, verbose_name='شامل مالیات')),
                ('include_in_overtime', models.BooleanField(default=False, verbose_name='شامل اضافه کاری')),
            ],
            options={
                'verbose_name': 'ایتم حقوقی',
                'verbose_name_plural': 'ایتم های حقوقی',
                'db_table': 'salary_item',
            },
        ),
    ]
