# Generated by Django 5.2 on 2025-04-17 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary_item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryitem',
            old_name='name',
            new_name='english_name',
        ),
    ]
