# Generated by Django 5.2 on 2025-04-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary_item', '0002_rename_name_salaryitem_english_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaryitem',
            options={'verbose_name': 'ایتم حقوقی', 'verbose_name_plural': 'ایتم های حقوقی'},
        ),
    ]
