# Generated by Django 5.2 on 2025-04-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_item', '0003_alter_salaryitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryitem',
            name='include_in_overtime',
            field=models.BooleanField(default=False, verbose_name='شامل اضافه کاری'),
        ),
    ]
