# Generated by Django 5.2 on 2025-04-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary_tax_calculation', '0002_salarytaxcalculation_salary_tax_calculation_working_month_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarytaxcalculation',
            options={'verbose_name': 'محسابه مالیات حقوق', 'verbose_name_plural': 'محاسبه مالیات های حقوق ها'},
        ),
        migrations.AlterModelTable(
            name='salarytaxcalculation',
            table='salary_tax_calculation',
        ),
    ]
