# Generated by Django 5.2 on 2025-04-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_of_items', models.DecimalField(decimal_places=0, default=0, editable=False, max_digits=16)),
            ],
            options={
                'db_table': 'salary_calculation',
            },
        ),
    ]
