# Generated by Django 5.2 on 2025-04-17 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salary_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.IntegerField(default=0, editable=False, verbose_name='مالیات')),
                ('insurance', models.IntegerField(default=0, editable=False, verbose_name='بیمه')),
                ('base_wage', models.IntegerField(default=0, editable=False, verbose_name='حقوق مبنا')),
                ('overtime', models.IntegerField(default=0, editable=False, verbose_name='اضافه کار')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryCalculationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='salary_calculation.salarycalculation')),
                ('salary_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salary_item.salaryitem')),
            ],
        ),
    ]
