# Generated by Django 5.2 on 2025-04-17 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('salary_calculation', '0001_initial'),
        ('working_month', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycalculation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='کارمند'),
        ),
        migrations.AddField(
            model_name='salarycalculation',
            name='working_month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='working_month.workingmonth', verbose_name='ماه کاری'),
        ),
    ]
