# Generated by Django 5.2 on 2025-04-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_calculation', '0002_salarycalculation_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycalculation',
            name='insurance_employee_share',
            field=models.IntegerField(default=0, editable=False, verbose_name='ییمه سهم کارگر'),
        ),
        migrations.AddField(
            model_name='salarycalculation',
            name='insurance_employer_share',
            field=models.IntegerField(default=0, editable=False, verbose_name='ییمه سهم کارفرما'),
        ),
    ]
