# Generated by Django 5.2 on 2025-04-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_calculation', '0002_alter_salarycalculation_sum_of_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarycalculation',
            name='sum_of_items',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
