# Generated by Django 5.2 on 2025-04-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_calculation', '0003_alter_salarycalculation_sum_of_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarycalculationitem',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
