# Generated by Django 5.2 on 2025-04-17 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_workload', '0003_alter_employeeworkload_employee_workload_working_month'),
        ('salary_calculation', '0003_salarycalculation_insurance_employee_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycalculation',
            name='employee_workload',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee_workload.employeeworkload', verbose_name='کارکرد کارمند'),
        ),
    ]
