# Generated by Django 5.2 on 2025-04-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary_calculation', '0004_salarycalculation_employee_workload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salarycalculation',
            options={'verbose_name': 'محاسبه حقوق', 'verbose_name_plural': 'محاسبه حقوق ها'},
        ),
        migrations.AlterModelTable(
            name='salarycalculation',
            table='salary_calculation',
        ),
    ]
