# Generated by Django 5.2 on 2025-04-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary_calculation', '0004_alter_salarycalculationitem_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salarycalculation',
            old_name='sum_of_items',
            new_name='tax',
        ),
    ]
