# Generated by Django 5.2 on 2025-04-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_calculation', '0005_alter_salarycalculation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarycalculation',
            name='insurance',
            field=models.IntegerField(default=0, editable=False, verbose_name='مجموع شامل بیمه'),
        ),
    ]
