# Generated by Django 5.2 on 2025-04-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_calculation', '0005_rename_sum_of_items_salarycalculation_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycalculation',
            name='insurance',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
