# Generated by Django 5.2 on 2025-04-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary_calculation', '0006_salarycalculation_insurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarycalculation',
            name='insurance',
        ),
    ]
