# Generated by Django 5.2 on 2025-04-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_calculation', '0007_remove_salarycalculation_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycalculation',
            name='insurance',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
