# Generated by Django 5.2 on 2025-04-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_calculation', '0008_salarycalculation_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycalculation',
            name='base_wage',
            field=models.IntegerField(default=0, editable=False, verbose_name='حقوق مبنا'),
        ),
        migrations.AddField(
            model_name='salarycalculation',
            name='over_time',
            field=models.IntegerField(default=0, editable=False, verbose_name='اضافه کار'),
        ),
        migrations.AlterField(
            model_name='salarycalculation',
            name='insurance',
            field=models.IntegerField(default=0, editable=False, verbose_name='بیمه'),
        ),
        migrations.AlterField(
            model_name='salarycalculation',
            name='tax',
            field=models.IntegerField(default=0, editable=False, verbose_name='مالیات'),
        ),
    ]
