# Generated by Django 5.2 on 2025-04-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_calculation', '0009_salarycalculation_base_wage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarycalculation',
            name='base_wage',
        ),
        migrations.RemoveField(
            model_name='salarycalculation',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='salarycalculation',
            name='over_time',
        ),
        migrations.AlterField(
            model_name='salarycalculation',
            name='tax',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
