# Generated by Django 5.2 on 2025-04-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary_calculation', '0010_remove_salarycalculation_base_wage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycalculation',
            name='base_wage',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='salarycalculation',
            name='insurance',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='salarycalculation',
            name='overtime',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
