# Generated by Django 5.2 on 2025-04-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingMonth',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('working_month_year', models.CharField(blank=True, choices=[('1396', '1396'), ('1397', '1397'), ('1398', '1398'), ('1399', '1399'), ('1400', '1400'), ('1401', '1401'), ('1402', '1402'), ('1403', '1403'), ('1404', '1404')], default=1404, max_length=4, null=True)),
                ('working_month_name', models.CharField(blank=True, choices=[('01', 'فروردین'), ('02', 'اردیبهشت'), ('03', 'خرداد'), ('04', 'تیر'), ('05', 'مرداد'), ('06', 'شهریور'), ('07', 'مهر'), ('08', 'آبان'), ('09', 'آذر'), ('10', 'دی'), ('11', 'بهمن'), ('12', 'اسفند')], max_length=2, null=True)),
                ('working_month_and_year', models.CharField(blank=True, editable=False, max_length=6, null=True)),
            ],
            options={
                'db_table': 'working_month',
            },
        ),
    ]
