# Generated by Django 5.2 on 2025-04-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('working_month', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingmonth',
            options={'verbose_name': 'ماه کاری', 'verbose_name_plural': 'ماه های کاری'},
        ),
    ]
